version: "3"

services:
  web:
    build: .
    command: npm run prestart
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/books
  
networks:
  app-network:
    driver: bridge
